version: "3"

services:
  mediapipe:
  
    # ビルドに使用するイメージの設定。
    image: ao2324/mediapipe

    # マウントするディレクトリの設定。
    volumes:
      - type:   bind
        source: "./app"
        target: "/usr/src/app/"

    # ディレクトリを移動。
    working_dir: /usr/src/app

    # "docker-compose up"で実行されるコマンド。
    command: python3 ./pose.py